jobSample = [
    "What are the key responsibilities of a Software Engineer?",
    "What qualifications are required for a Data Scientist?",
    "What skills are needed for a Project Manager?",
    "What is the job description of a Marketing Specialist?",
    "What experience is necessary for a UX Designer?",
    "What are the duties of a Financial Analyst?",
    "What certifications are beneficial for a Network Engineer?",
    "What is the role of a Human Resources Manager?",
    "What are the requirements for a Business Analyst?",
    "What does a typical day look like for a Graphic Designer?",
    "What are the main tasks of a Sales Manager?",
    "What qualifications do you need to become a Product Manager?",
    "What skills are essential for a Content Writer?",
    "What is the job description of a Customer Service Representative?",
    "What experience is required for a Software Developer?",
    "What are the responsibilities of a Digital Marketing Manager?",
    "What certifications are needed for a Cybersecurity Specialist?",
    "What is the role of a Data Analyst?",
    "What qualifications are necessary for a Mechanical Engineer?",
    "What skills are important for a Social Media Manager?",
    "What are the duties of an Electrical Engineer?",
    "What experience is beneficial for a Quality Assurance Tester?",
    "What is the job description of a Database Administrator?",
    "What are the main tasks of a Systems Analyst?",
    "What qualifications do you need to become a Civil Engineer?",
    "What skills are essential for a Technical Support Specialist?",
    "What is the role of a Business Development Manager?",
    "What are the requirements for a Web Developer?",
    "What does a typical day look like for a Data Engineer?",
    "What are the main tasks of a Cloud Architect?",
    "What qualifications are necessary for a Machine Learning Engineer?",
    "What skills are important for a SEO Specialist?",
    "What are the duties of a Mobile App Developer?",
    "What experience is required for a DevOps Engineer?",
    "What is the job description of a IT Support Specialist?",
    "What are the responsibilities of a Network Administrator?",
    "What certifications are beneficial for a Blockchain Developer?",
    "What is the role of a Product Designer?",
    "What qualifications are needed for a Game Developer?",
    "What skills are essential for a Copywriter?",
    "What is the job description of a Operations Manager?",
    "What experience is necessary for a Cloud Engineer?",
    "What are the duties of a Front-End Developer?",
    "What qualifications do you need to become a Back-End Developer?",
    "What skills are important for a Full-Stack Developer?",
    "What are the main tasks of a Data Scientist?",
    "What experience is beneficial for a AI Researcher?",
    "What is the role of a Robotics Engineer?",
    "What qualifications are necessary for a Bioinformatics Specialist?",
    "What skills are essential for a Technical Writer?",
    "What are the duties of a Systems Engineer?",
    "What experience is required for a IT Project Manager?",
    "What is the job description of a Software Architect?",
    "What are the responsibilities of a Security Analyst?",
    "What certifications are needed for a Penetration Tester?",
    "What is the role of a IT Consultant?",
    "What qualifications are necessary for a Network Security Engineer?",
    "What skills are important for a Data Warehouse Specialist?",
    "What are the duties of a IT Auditor?",
    "What experience is beneficial for a ERP Consultant?",
    "What is the job description of a CRM Specialist?",
    "What are the main tasks of a IT Trainer?",
    "What qualifications do you need to become a IT Manager?",
    "What skills are essential for a Help Desk Technician?",
    "What is the role of a IT Coordinator?",
    "What are the requirements for a IT Director?",
    "What does a typical day look like for a IT Analyst?",
    "What are the main tasks of a IT Support Engineer?",
    "What qualifications are necessary for a IT Operations Manager?",
    "What skills are important for a IT Infrastructure Manager?",
    "What are the duties of a IT Service Manager?",
    "What experience is required for a IT Systems Administrator?",
    "What is the job description of a IT Network Engineer?",
    "What are the responsibilities of a IT Security Manager?",
    "What certifications are beneficial for a IT Compliance Manager?",
    "What is the role of a IT Risk Manager?",
    "What qualifications are needed for a IT Governance Manager?",
    "What skills are essential for a IT Strategy Manager?",
    "What is the job description of a IT Change Manager?",
    "What experience is necessary for a IT Configuration Manager?",
    "What are the duties of a IT Release Manager?",
    "What qualifications do you need to become a IT Incident Manager?",
    "What skills are important for a IT Problem Manager?",
    "What are the main tasks of a IT Capacity Manager?",
    "What experience is beneficial for a IT Availability Manager?",
    "What is the role of a IT Continuity Manager?",
    "What qualifications are necessary for a IT Service Desk Manager?",
    "What skills are essential for a IT Asset Manager?",
    "What are the duties of a IT Vendor Manager?",
    "What experience is required for a IT Contract Manager?",
    "What is the job description of a IT Procurement Manager?",
    "What are the responsibilities of a IT Financial Manager?",
    "What certifications are needed for a IT Budget Manager?",
    "What is the role of a IT Cost Manager?",
    "What qualifications are necessary for a IT Performance Manager?",
    "What skills are important for a IT Quality Manager?",
    "What are the duties of a IT Process Manager?",
    "What experience is beneficial for a IT Project Coordinator?",
    "What is the job description of a IT Program Manager?",
    "What are the main tasks of a IT Portfolio Manager?"
]


chitchatSample = [
    "What is the weather like today?",
    "How hot is it outside?",
    "Will it rain tomorrow?",
    "What is the current temperature?",
    "Can you tell me the current weather conditions?",
    "Will it be sunny this weekend?",
    "What was the temperature yesterday?",
    "How cold will it be tonight?",
    "Who was the first president of the United States?",
    "When did World War II end?",
    "Can you tell me about the history of the internet?",
    "When was the Eiffel Tower built?",
    "Who invented the telephone?",
    "What is your name?",
    "Do you have a name?",
    "What should I call you?",
    "Who created you?",
    "How old are you?",
    "Can you tell me an interesting fact?",
    "Do you know any interesting riddles?",
    "What is your favorite color?",
    "What is your favorite movie?",
    "Do you have any hobbies?",
    "What is the meaning of life?",
    "Can you tell me a joke?",
    "What is the capital of France?",
    "What is the world population?",
    "How many continents are there?",
    "Who wrote 'To Kill a Mockingbird'?",
    "Can you give me a quote from Albert Einstein?"
]